services:
  - type: web
    name: showsphere
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn showsphere.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: showsphere_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false

databases:
  - name: showsphere_db
    databaseName: showsphere
    user: showsphere_user
    plan: free # Optional: specify plan if needed (e.g. starter, free)
